---
- name: "Create nginx conf file"
  template:
    src=nginx.conf.j2 dest="{{ cmdb_conf_dir }}/nginx-default.conf"


- name: start nginx container
  docker_container:
    name: proxy
    image: "{{ cmdb_nginx_image }}"
    detach: true
    state: started
    network_mode: "host"
    volumes:
    - "{{ cmdb_conf_dir }}/nginx-default.conf:/etc/nginx/conf.d/default.conf"
    restart_policy: always
  
