---
# tasks file for indigopaas.slam

- name: "create directory path to store the configuration files" 
  file:
    path: "{{ im_conf_dir }}"
    state: directory
    mode: 0755

- name: "Create mysql container env file"
  template:
    src=mysql-env.j2 dest="{{ im_conf_dir }}/.mysqlenv"


- name: Start mysql
  docker_container: 
    name: mysql
    image: "{{ mysql_image }}"
    detach: true
    state: started
    network_mode: "host"
    volumes:
    - "{{ mysql_data_dir }}:/var/lib/mysql"
    restart_policy: always
    env_file: "{{ im_conf_dir }}/.mysqlenv"

- name: wait for mysql to be up and running 
  wait_for: 
     host: "localhost" 
     port: "3306"
     delay: 20
     timeout: 600
     connect_timeout: 10

- name: "Create IM container env file"
  template:
    src=im-env.j2 dest="{{ im_conf_dir }}/.imenv"


- name: Start IM container
  docker_container:
    name: im
    image: "{{ im_image }}"
    detach: true
    state: started
    network_mode: "host"
    volumes:
    - "{{im_conf_dir}}:/etc/im"
    - "{{im_conf_dir}}/ansible.cfg:/etc/ansible/ansible.cfg"
    restart_policy: always
    env_file: "{{ im_conf_dir }}/.imenv"

